VAR MCName = "???"
VAR Pokemon = ""    
VAR ItemP1 = 0
VAR PrologStart = false
VAR P1Complete = false
VAR P1Start = false
VAR P2Complete = false
VAR claimP3 = false
VAR P4Digit1= 0
VAR P4Digit2= 0
VAR P4Digit3= 0
VAR P4Digit4= 0
VAR P7Start = false
VAR P7Complete = false
VAR Level = 1